.TH "biditex" 1
.SH NAME
biditex \- automatic bidirectional support for LaTeX.
.SH SYNOPSIS
.B biditex
[ parameters ] [ inputfilename ]
.SH DESCRIPTION
This program adds bidirectional tags \\L{} or \\R{} to LaTeX source according to
unicode algorithm. It was designed to work together with ivritex.
.SH OPTIONS
The program receives as input latex file that includes mixed English and Hebrew. In case no input file
is given standard input is used.
.TP
.B \-o file_name.tex
Output file name.
.TP
.B \-e utf8 | iso8859-8 | cp1255
Source and target encoding. Default encoding is UTF-8.
.TP
.B \-m
Replace '\-\-'  and  '---' by '\\L{\-\-}' and '\\L{\-\-\-}'. This fixes the \\emdash and \\endash
issue in Culmus David font that is supported with ivritex.
.TP
.SH "SEE ALSO"
The documentation of the biditex - biditex-doc.pdf
.SH BUGS
TBD
.SH AUTHOR
Artyom Tonkikh 2007
